#!/bin/sh

export TEST_PHP_EXECUTABLE=/usr/bin/php

if [ -z $1 ]; then
    test=`pwd`
else
    test=$1
fi


# /usr/local/src/php-7.0.9/run-tests.php -m --temp-source /tmp $1
 /usr/local/src/php-7.0.9/run-tests.php --temp-source /tmp $1
